USE [master]
GO
/****** Object:  Database [YS]    Script Date: 9/3/2017 9:04:33 PM ******/
CREATE DATABASE [YS]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'YS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MYSQLSERVER\MSSQL\DATA\YS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'YS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MYSQLSERVER\MSSQL\DATA\YS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [YS] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [YS] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [YS] SET ANSI_NULLS OFF
GO
ALTER DATABASE [YS] SET ANSI_PADDING OFF
GO
ALTER DATABASE [YS] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [YS] SET ARITHABORT OFF
GO
ALTER DATABASE [YS] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [YS] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [YS] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [YS] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [YS] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [YS] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [YS] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [YS] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [YS] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [YS] SET  DISABLE_BROKER
GO
ALTER DATABASE [YS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [YS] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [YS] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [YS] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [YS] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [YS] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [YS] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [YS] SET RECOVERY FULL
GO
ALTER DATABASE [YS] SET  MULTI_USER
GO
ALTER DATABASE [YS] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [YS] SET DB_CHAINING OFF
GO
ALTER DATABASE [YS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [YS] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [YS] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [YS] SET QUERY_STORE = OFF
GO
USE [YS]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [YS]
GO
/****** Object:  Table [dbo].[ActivityHeader]    Script Date: 9/3/2017 9:04:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ActivityHeader](
	[activity_id] [uniqueidentifier] NOT NULL,
	[user_id] [uniqueidentifier] NOT NULL,
	[activity_time] [datetime] NOT NULL,
	[activity_type_id] [int] NOT NULL,
	[hint_id] [int] NOT NULL,
	[update_date] [datetime] NULL,
	[update_by] [nchar](50) NULL,
 CONSTRAINT [PK_ActivityHeader] PRIMARY KEY CLUSTERED
(
	[activity_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Food]    Script Date: 9/3/2017 9:04:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Food](
	[food_id] [uniqueidentifier] NOT NULL,
	[food_name] [nvarchar](100) NULL,
 CONSTRAINT [PK_Food] PRIMARY KEY CLUSTERED
(
	[food_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Program]    Script Date: 9/3/2017 9:04:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Program](
	[program_id] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Programs] PRIMARY KEY CLUSTERED
(
	[program_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 9/3/2017 9:04:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[user_id] [uniqueidentifier] NOT NULL,
	[app_user_id] [int] NOT NULL,
	[user_name] [nvarchar](100) NULL,
	[first_name] [nvarchar](100) NULL,
	[last_name] [nvarchar](100) NULL,
	[email] [nvarchar](300) NULL,
	[weight] [decimal](4, 2) NULL,
	[age] [decimal](3, 1) NULL,
	[gender] [char](1) NULL,
	[update_time] [datetime] NULL,
	[update_by] [nchar](50) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserProgram]    Script Date: 9/3/2017 9:04:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserProgram](
	[user_program_id] [uniqueidentifier] NOT NULL,
	[user_id] [uniqueidentifier] NOT NULL,
	[program_id] [uniqueidentifier] NOT NULL,
	[start_date] [datetime] NULL,
	[end_date] [datetime] NULL,
 CONSTRAINT [PK_UserProgram] PRIMARY KEY CLUSTERED
(
	[user_program_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UserProgram]  WITH CHECK ADD  CONSTRAINT [FK_UserProgram_Program] FOREIGN KEY([program_id])
REFERENCES [dbo].[Program] ([program_id])
GO
ALTER TABLE [dbo].[UserProgram] CHECK CONSTRAINT [FK_UserProgram_Program]
GO
USE [master]
GO
ALTER DATABASE [YS] SET  READ_WRITE
GO
